name: Auto Generate and Replace Reference Files

on: [push]

jobs:
  generate_reference-and-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Setup Java"
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11
          cache: 'gradle'
      - name: Build with Gradle
        run: ./gradlew
      - name: Generate reference
        run: ./gradlew javadoc
      - name: Setup git
        env:
            EMAIL: ${{ secrets.EMAIL }}
        run: |
          git config --global user.email "$EMAIL"
          git config --global user.name "tanaka-kokoro"
          
      - name: Commit docs
        run: |
          if ! git diff --exit-code --quiet
          then
            git add .
            git commit -m "Auto replace reference files"
            git pull
            git push origin develop
          fi
      - name: zip docs
        run: zip -r docs.zip docs/
      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: docs
          path: docs.zip